---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/going-serverless
  label: Going serverless
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: media_upload
public_path: "/medias"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.38.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.38.1
  preview_output_directory: public
  output_directory: public
version: 0.38.1
