---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: media_upload
public_path: "/medias"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
